### ISSUE TITLE
Subway isn't colorful enough

### ISSUE THREAD

**Issue by sheeley** [nucleardreamer/tdc#1]
:confetti_ball:

**Comment by nucleardreamer** [comment]
fixed in #idontgiveafuck

**Comment by sheeley** [comment]
plz repoen

**Comment by nucleardreamer** [comment]
Please submit a pull request that I will let sit there forever.

**Comment by sheeley** [comment]
after considering that i'd have to actually fork, commit, and submit pr, nevermind.
